### ISSUE TITLE
Not Compatible with IntelliJ IDEA 2021.3.1 

### ISSUE THREAD

**Issue by Monotoba** [mike42/6502-assembly-intellij#3]
I hope you will be updating this. I find it very useful for retro computing and SoC using the 65xx architectures.

**Comment by mike42** [comment]
Thanks @Monotoba - I've corrected the `plugin.xml`. 

In plugin version 1.2 we had:

```
<idea-version since-build="211.6693" until-build="212.*" />
```

This stopped working when a new version came out. In plugin version 1.3 it is now:

```
<idea-version since-build="211.6693" />
```

I expect this will resolve the problem. The update is currently pending approval from JetBrains before it will appear in the marketplace. :+1:

**Comment by Monotoba** [comment]
Thank you for the rapid response! Please keep up the good work and if I can buy you a cup of coffee sometime let me know.
