### ISSUE TITLE
Not compatible with CLion?

### ISSUE THREAD

**Issue by IAmJulianAcosta** [mike42/6502-assembly-intellij#4]
Hi, is this plugin compatible with CLion? It seems to support the other Jetbrains IDEs but this one:

## Webstorm
![image](https://user-images.githubusercontent.com/1844640/165212299-f736ec98-9ba5-4e06-836a-dd7d6b0412d0.png)

## CLion
![image](https://user-images.githubusercontent.com/1844640/165212340-8528f55a-93ea-4233-9a4c-78e6a7f135c1.png)

**Comment by mike42** [comment]
No it is not, see #1 and #2

When installed on CLion, a conflict is reported between this plugin and the built-in C/C++ plugin, and it prompts the user to disable one or the other. It is not possible to disable the built-in plugin, so the user has no choice but to disable 6502 assembly plugin.

I don't know if it's possible to fix this, so as of version 1.3, I've updated the plugin.xml to list the incompatibility.
